export const SET_COUNTERS = "SET_COUNTERS";
export const SET_NEW_COUNTER_DIALOG = "SET_NEW_COUNTER_DIALOG";
export const SET_RENAME_DIALOG = "SET_RENAME_DIALOG";
export const SET_ID_TO_EDIT = "SET_ID_TO_EDIT";
export const SET_CONFIRM_DELETE_DIALOG = "SET_CONFIRM_DELETE_DIALOG";
export const SET_ADJUST_COUNT_DIALOG = "SET_ADJUST_COUNT_DIALOG";
export const SET_CREDITS_DIALOG = "SET_CREDITS_DIALOG";
